spring:
  application:
    name: filenet-core
  datasource:
#    url: jdbc:mysql://carloscardona:3306/filenet?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: filenet
#    password: filenet
#    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

server:
#  port: 80
  servlet:
    context-path: /filenet
#    context-path: /carga-usuarios